// jo id likhi bhi oh likhni hi chahhide taki  data access krne ch asssni hone id dekaii uno  
const items = [
    {
        id: '001',
        image: 'images/2.jpeg',
        company: 'Dimond jewellery',
        item_name: 'Rhodium-Plated CZ Floral Studs',
        original_price: 100000000,
        current_price: 58000000,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },
    {
        id: '002',
        image: "images/3.jpeg",
        company: 'ZARA',
        item_name: 'Women party wear Dress',
        original_price: 2599,
        current_price: 1507,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.3,
            count: 24,
        },
    },
    {
        id: '003',
        image: 'images/4.jpeg',
        company: 'H & M',
        item_name: 'H&M T-Shirt',
        original_price: 1599,
        current_price: 495,
        discount_percentage: 69,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.1,
            count: 249,
        },
    },
    {
        id: '004',
        image: 'images/5.jpeg',
        company: 'Girly',
        item_name: 'Baby Girl red suit',
        original_price: 999,
        current_price: 999,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 5.0,
            count: 10,
        },
    },
    {
        id: '005',
        image: 'images/6.jpeg',
        company: 'Buster',
        item_name: 'Gym Dumbell',
        original_price: 10399,
        current_price: 4089,
        discount_percentage: 65,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 3500,
        },
    },
    {
        id: '006',
        image: 'images/7.jpeg',
        company: 'Loui vuitton',
        item_name: 'Loui Vuitton Trainers shoes',
        original_price: 200995,
        current_price: 20995,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 5.0,
            count: 65045,
        },
    },
    {
        id: '007',
        image: 'images/8.jpeg',
        company: 'The Royal Enfield',
        item_name: 'Java 250CC',
        original_price: 150099,
        current_price: 60039,
        discount_percentage: 60,
        delivery_date: '10 Oct 2023',

        rating: {
            stars: 4.2,
            count: 388,
        },
    },
    {
        id: '008',
        image: 'images/9.jpeg',
        company: 'Bugatti',
        item_name: 'Bugati sheron',
        original_price: 285000000,
        current_price: 14200000,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    }
];
